---
# Source: api/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name:  api
  namespace: "chuck"
spec:
  selector:
    app: api
  ports:
    - name: http
      port: 80
      targetPort: 8080
---
# Source: api/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: chuck
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: docker.io/dimssss/chuck-api:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: DB_HOST
              value: "mysql-db"
            - name: DB_NAME
              value: "chuck"
            - name: DB_USER
              value: "chuck"
            - name: DB_PASS
              value: "chuck"

---
# Source: api/templates/route.yaml
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: api
  namespace: chuck
spec:
  host: chuck-api.apps.b.okto.ocplab.io
  port:
    targetPort:  http
  to:
    kind: Service
    name: api
    weight: 100
status:
  ingress: []

