apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chuck-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: chuck-project
  destination:
    namespace: chuck
    server: 'https://kubernetes.default.svc'
  source:
    path: chuck-app
    repoURL: 'https://github.com/Dimss/chuck-forum19-demo.git'
    targetRevision: master
    directory:
      recurse: true
  syncPolicy:
    automated:
      selfHeal: true