apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chuck-db
  namespace: gitops-infra
spec:
  project: gitops-infra
  destination:
    namespace: chuck
    server: 'https://kubernetes.default.svc'
  source:
    path: project
    repoURL: 'https://github.com/Dimss/chuck-forum19-demo.git'
    targetRevision: HEAD
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

