apiVersion: v1
kind: Secret
metadata:
  labels:
    template: mysql-ephemeral-template
  name: mysql-db
  namespace: chuck
stringData:
  database-name: chuck
  database-password: chuck
  database-root-password: VDcnNwDLUFxVYKgR
  database-user: chuck
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-db
  namespace: chuck
spec:
  ports:
  - name: mysql
    port: 3306
    protocol: TCP
  selector:
    app: mysql-db
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: "apps/v1"
kind: Deployment
metadata:
  labels:
    app: "mysql-db"
  name: "mysql-db"
  namespace: chuck
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "mysql-db"
  template:
    metadata:
      labels:
        app: "mysql-db"
    spec:
      containers:
      - name: "chuck-db"
        image: "registry.redhat.io/rhscl/mysql-57-rhel7:latest"
        imagePullPolicy: Always
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              key: database-user
              name: mysql-db
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: database-password
              name: mysql-db
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: database-root-password
              name: mysql-db
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              key: database-name
              name: mysql-db