apiVersion: "apps/v1"
kind: Deployment
metadata:
  labels:
    app: "chuck-ui"
  name: "chuck-ui"
  namespace: chuck
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: "chuck-ui"
        version: v1
    spec:
      containers:
      - name: "chuck-ui"
        image: "docker.io/dimssss/chuck-ui:latest"
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: API_URL
          value: "http://chuck-api.apps.b.okto.ocplab.io"